// Code generated by build-blitz.sh. DO NOT EDIT.

//go:build linux && arm

package lib

/*
#cgo LDFLAGS: -L${SRCDIR} -lblitz -lfontconfig -lfreetype -ldl -lgcc_s -lutil -lrt -lpthread -lm
*/
import "C"
