// Code generated by build-blitz.sh. DO NOT EDIT.

//go:build windows && amd64

package blitz

// Blank import for the link only: the package has no API, it just carries the
// windows-amd64 archives and the #cgo LDFLAGS naming them. Because this file is
// build-tagged, the go command never downloads the other five platforms'
// modules when building for this one.
import _ "github.com/xo/blitz/libblitz/windows-amd64"
