// Code generated by build-blitz.sh. DO NOT EDIT.

//go:build darwin && arm64

package lib

/*
#cgo LDFLAGS: -L${SRCDIR} -lblitz -framework Security -framework CoreFoundation -framework Foundation -framework CoreText -lobjc -liconv -lm
*/
import "C"
