// Code generated by build-blitz.sh. DO NOT EDIT.

//go:build windows && amd64

package lib

/*
#cgo LDFLAGS: -L${SRCDIR} -lblitz -lws2_32 -lbcrypt -lcrypt32 -lsecur32 -lncrypt -lntdll -luserenv -lkernel32 -ldbghelp -lole32 -loleaut32 -ldwrite -lgdi32 -lusp10 -lshell32 -ladvapi32 -luuid -lmsvcrt -lpthread
*/
import "C"
