// Package lib ships the prebuilt Blitz static archives for linux-arm64 and the
// cgo link flags that go with them. It has no API: import it for its side
// effect on the link, which is what github.com/xo/blitz does.
//
// Code generated by build-blitz.sh. DO NOT EDIT.
package lib
