// Code generated by build-blitz.sh. DO NOT EDIT.

//go:build linux && arm64

package lib

/*
#cgo LDFLAGS: -L${SRCDIR} -Wl,--start-group -lblitz0 -lblitz1 -Wl,--end-group -lfontconfig -lfreetype -ldl -lgcc_s -lutil -lrt -lpthread -lm
*/
import "C"
